import { expandToComponentDemand, resolveSellable, compositesBlockedBy } from '@/lib/inventory-mapping';
const B='bundle_glass_skin_starter_onetime';
const A='torriden_dive_in_serum_onetime';
const R='restock_beplain_mung_bean_cleansing_oil_200ml_monthly';
const t=(n:string,v:any)=>console.log(n,JSON.stringify(v));
t('single bundle', expandToComponentDemand([{priceId:B,quantity:1}]).demand);
t('bundle x3', expandToComponentDemand([{priceId:B,quantity:3}]).demand.find(d=>d.sku===A));
t('mixed cart A x1 + bundle x2', expandToComponentDemand([{priceId:A,quantity:1},{priceId:B,quantity:2}]).demand.find(d=>d.sku===A));
t('restock', expandToComponentDemand([{priceId:R,quantity:1}]).demand);
t('membership', expandToComponentDemand([{priceId:'circle_monthly',quantity:1}]));
t('unknown', expandToComponentDemand([{priceId:'bundle_mystery_box',quantity:1}]).unmapped);
t('composite blocked by sold-out component', compositesBlockedBy([A]));
t('composite unaffected by unrelated sold out', compositesBlockedBy(['aestura_a_cica_moisture_toner_onetime']));
t('physical', resolveSellable(A));
