/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ClubRouteImport } from './routes/club'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RestockRouteImport } from './routes/restock'
import { Route as ReturnsPolicyRouteImport } from './routes/returns-policy'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SkinConcernsRouteImport } from './routes/skin-concerns'
import { Route as TrackRouteImport } from './routes/track'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminGuideLinksRouteImport } from './routes/admin.guide-links'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminSignalsRouteImport } from './routes/admin.signals'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as GroceryListIndexRouteImport } from './routes/grocery-list.index'
import { Route as GroceryListSlugRouteImport } from './routes/grocery-list.$slug'
import { Route as GuideProductIdRouteImport } from './routes/guide.$productId'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnSlugRouteImport } from './routes/learn.$slug'
import { Route as LearnHubRouteImport } from './routes/learn.hub'
import { Route as ProductSlugRouteImport } from './routes/product.$slug'
import { Route as RoutinesIndexRouteImport } from './routes/routines.index'
import { Route as RoutinesBundleIdRouteImport } from './routes/routines.$bundleId'
import { Route as AdminIssuesIdRouteImport } from './routes/admin.issues.$id'
import { Route as LearnArticleSlugRouteImport } from './routes/learn.article.$slug'
import { Route as ApiPublicIssueCoverIdRouteImport } from './routes/api/public/issue-cover.$id'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicSignalsHarvestRouteImport } from './routes/api/public/signals/harvest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RestockRoute = RestockRouteImport.update({
  id: '/restock',
  path: '/restock',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsPolicyRoute = ReturnsPolicyRouteImport.update({
  id: '/returns-policy',
  path: '/returns-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SkinConcernsRoute = SkinConcernsRouteImport.update({
  id: '/skin-concerns',
  path: '/skin-concerns',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminGuideLinksRoute = AdminGuideLinksRouteImport.update({
  id: '/admin/guide-links',
  path: '/admin/guide-links',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSignalsRoute = AdminSignalsRouteImport.update({
  id: '/admin/signals',
  path: '/admin/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => CheckoutRoute,
} as any)
const GroceryListIndexRoute = GroceryListIndexRouteImport.update({
  id: '/grocery-list/',
  path: '/grocery-list/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroceryListSlugRoute = GroceryListSlugRouteImport.update({
  id: '/grocery-list/$slug',
  path: '/grocery-list/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideProductIdRoute = GuideProductIdRouteImport.update({
  id: '/guide/$productId',
  path: '/guide/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnSlugRoute = LearnSlugRouteImport.update({
  id: '/learn/$slug',
  path: '/learn/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnHubRoute = LearnHubRouteImport.update({
  id: '/learn/hub',
  path: '/learn/hub',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSlugRoute = ProductSlugRouteImport.update({
  id: '/product/$slug',
  path: '/product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesIndexRoute = RoutinesIndexRouteImport.update({
  id: '/routines/',
  path: '/routines/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesBundleIdRoute = RoutinesBundleIdRouteImport.update({
  id: '/routines/$bundleId',
  path: '/routines/$bundleId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIssuesIdRoute = AdminIssuesIdRouteImport.update({
  id: '/admin/issues/$id',
  path: '/admin/issues/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnArticleSlugRoute = LearnArticleSlugRouteImport.update({
  id: '/learn/article/$slug',
  path: '/learn/article/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicIssueCoverIdRoute = ApiPublicIssueCoverIdRouteImport.update({
  id: '/api/public/issue-cover/$id',
  path: '/api/public/issue-cover/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSignalsHarvestRoute = ApiPublicSignalsHarvestRouteImport.update({
  id: '/api/public/signals/harvest',
  path: '/api/public/signals/harvest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/club': typeof ClubRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/journey': typeof JourneyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/restock': typeof RestockRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skin-concerns': typeof SkinConcernsRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
  '/admin/guide-links': typeof AdminGuideLinksRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/signals': typeof AdminSignalsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/grocery-list/$slug': typeof GroceryListSlugRoute
  '/guide/$productId': typeof GuideProductIdRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/hub': typeof LearnHubRoute
  '/product/$slug': typeof ProductSlugRoute
  '/routines/$bundleId': typeof RoutinesBundleIdRoute
  '/blog/': typeof BlogIndexRoute
  '/grocery-list/': typeof GroceryListIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/routines/': typeof RoutinesIndexRoute
  '/admin/issues/$id': typeof AdminIssuesIdRoute
  '/learn/article/$slug': typeof LearnArticleSlugRoute
  '/api/public/issue-cover/$id': typeof ApiPublicIssueCoverIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/signals/harvest': typeof ApiPublicSignalsHarvestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/club': typeof ClubRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/journey': typeof JourneyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/restock': typeof RestockRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skin-concerns': typeof SkinConcernsRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
  '/admin/guide-links': typeof AdminGuideLinksRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/signals': typeof AdminSignalsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/grocery-list/$slug': typeof GroceryListSlugRoute
  '/guide/$productId': typeof GuideProductIdRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/hub': typeof LearnHubRoute
  '/product/$slug': typeof ProductSlugRoute
  '/routines/$bundleId': typeof RoutinesBundleIdRoute
  '/blog': typeof BlogIndexRoute
  '/grocery-list': typeof GroceryListIndexRoute
  '/learn': typeof LearnIndexRoute
  '/routines': typeof RoutinesIndexRoute
  '/admin/issues/$id': typeof AdminIssuesIdRoute
  '/learn/article/$slug': typeof LearnArticleSlugRoute
  '/api/public/issue-cover/$id': typeof ApiPublicIssueCoverIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/signals/harvest': typeof ApiPublicSignalsHarvestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/brands': typeof BrandsRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/club': typeof ClubRoute
  '/consultation': typeof ConsultationRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/journey': typeof JourneyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/restock': typeof RestockRoute
  '/returns-policy': typeof ReturnsPolicyRoute
  '/reviews': typeof ReviewsRoute
  '/search': typeof SearchRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/skin-concerns': typeof SkinConcernsRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
  '/admin/guide-links': typeof AdminGuideLinksRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/signals': typeof AdminSignalsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/grocery-list/$slug': typeof GroceryListSlugRoute
  '/guide/$productId': typeof GuideProductIdRoute
  '/learn/$slug': typeof LearnSlugRoute
  '/learn/hub': typeof LearnHubRoute
  '/product/$slug': typeof ProductSlugRoute
  '/routines/$bundleId': typeof RoutinesBundleIdRoute
  '/blog/': typeof BlogIndexRoute
  '/grocery-list/': typeof GroceryListIndexRoute
  '/learn/': typeof LearnIndexRoute
  '/routines/': typeof RoutinesIndexRoute
  '/admin/issues/$id': typeof AdminIssuesIdRoute
  '/learn/article/$slug': typeof LearnArticleSlugRoute
  '/api/public/issue-cover/$id': typeof ApiPublicIssueCoverIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/signals/harvest': typeof ApiPublicSignalsHarvestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/brands'
    | '/checkout'
    | '/club'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/journey'
    | '/privacy-policy'
    | '/restock'
    | '/returns-policy'
    | '/reviews'
    | '/search'
    | '/shipping-policy'
    | '/shop'
    | '/sitemap.xml'
    | '/skin-concerns'
    | '/track'
    | '/wishlist'
    | '/admin/guide-links'
    | '/admin/orders'
    | '/admin/reviews'
    | '/admin/signals'
    | '/blog/$slug'
    | '/checkout/return'
    | '/grocery-list/$slug'
    | '/guide/$productId'
    | '/learn/$slug'
    | '/learn/hub'
    | '/product/$slug'
    | '/routines/$bundleId'
    | '/blog/'
    | '/grocery-list/'
    | '/learn/'
    | '/routines/'
    | '/admin/issues/$id'
    | '/learn/article/$slug'
    | '/api/public/issue-cover/$id'
    | '/api/public/payments/webhook'
    | '/api/public/signals/harvest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/brands'
    | '/checkout'
    | '/club'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/journey'
    | '/privacy-policy'
    | '/restock'
    | '/returns-policy'
    | '/reviews'
    | '/search'
    | '/shipping-policy'
    | '/shop'
    | '/sitemap.xml'
    | '/skin-concerns'
    | '/track'
    | '/wishlist'
    | '/admin/guide-links'
    | '/admin/orders'
    | '/admin/reviews'
    | '/admin/signals'
    | '/blog/$slug'
    | '/checkout/return'
    | '/grocery-list/$slug'
    | '/guide/$productId'
    | '/learn/$slug'
    | '/learn/hub'
    | '/product/$slug'
    | '/routines/$bundleId'
    | '/blog'
    | '/grocery-list'
    | '/learn'
    | '/routines'
    | '/admin/issues/$id'
    | '/learn/article/$slug'
    | '/api/public/issue-cover/$id'
    | '/api/public/payments/webhook'
    | '/api/public/signals/harvest'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/brands'
    | '/checkout'
    | '/club'
    | '/consultation'
    | '/contact'
    | '/faq'
    | '/journey'
    | '/privacy-policy'
    | '/restock'
    | '/returns-policy'
    | '/reviews'
    | '/search'
    | '/shipping-policy'
    | '/shop'
    | '/sitemap.xml'
    | '/skin-concerns'
    | '/track'
    | '/wishlist'
    | '/admin/guide-links'
    | '/admin/orders'
    | '/admin/reviews'
    | '/admin/signals'
    | '/blog/$slug'
    | '/checkout/return'
    | '/grocery-list/$slug'
    | '/guide/$productId'
    | '/learn/$slug'
    | '/learn/hub'
    | '/product/$slug'
    | '/routines/$bundleId'
    | '/blog/'
    | '/grocery-list/'
    | '/learn/'
    | '/routines/'
    | '/admin/issues/$id'
    | '/learn/article/$slug'
    | '/api/public/issue-cover/$id'
    | '/api/public/payments/webhook'
    | '/api/public/signals/harvest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  BrandsRoute: typeof BrandsRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  ClubRoute: typeof ClubRoute
  ConsultationRoute: typeof ConsultationRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  JourneyRoute: typeof JourneyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RestockRoute: typeof RestockRoute
  ReturnsPolicyRoute: typeof ReturnsPolicyRoute
  ReviewsRoute: typeof ReviewsRoute
  SearchRoute: typeof SearchRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SkinConcernsRoute: typeof SkinConcernsRoute
  TrackRoute: typeof TrackRoute
  WishlistRoute: typeof WishlistRoute
  AdminGuideLinksRoute: typeof AdminGuideLinksRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSignalsRoute: typeof AdminSignalsRoute
  BlogSlugRoute: typeof BlogSlugRoute
  GroceryListSlugRoute: typeof GroceryListSlugRoute
  GuideProductIdRoute: typeof GuideProductIdRoute
  LearnSlugRoute: typeof LearnSlugRoute
  LearnHubRoute: typeof LearnHubRoute
  ProductSlugRoute: typeof ProductSlugRoute
  RoutinesBundleIdRoute: typeof RoutinesBundleIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  GroceryListIndexRoute: typeof GroceryListIndexRoute
  LearnIndexRoute: typeof LearnIndexRoute
  RoutinesIndexRoute: typeof RoutinesIndexRoute
  AdminIssuesIdRoute: typeof AdminIssuesIdRoute
  LearnArticleSlugRoute: typeof LearnArticleSlugRoute
  ApiPublicIssueCoverIdRoute: typeof ApiPublicIssueCoverIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicSignalsHarvestRoute: typeof ApiPublicSignalsHarvestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restock': {
      id: '/restock'
      path: '/restock'
      fullPath: '/restock'
      preLoaderRoute: typeof RestockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns-policy': {
      id: '/returns-policy'
      path: '/returns-policy'
      fullPath: '/returns-policy'
      preLoaderRoute: typeof ReturnsPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skin-concerns': {
      id: '/skin-concerns'
      path: '/skin-concerns'
      fullPath: '/skin-concerns'
      preLoaderRoute: typeof SkinConcernsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/guide-links': {
      id: '/admin/guide-links'
      path: '/admin/guide-links'
      fullPath: '/admin/guide-links'
      preLoaderRoute: typeof AdminGuideLinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/signals': {
      id: '/admin/signals'
      path: '/admin/signals'
      fullPath: '/admin/signals'
      preLoaderRoute: typeof AdminSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/grocery-list/': {
      id: '/grocery-list/'
      path: '/grocery-list'
      fullPath: '/grocery-list/'
      preLoaderRoute: typeof GroceryListIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grocery-list/$slug': {
      id: '/grocery-list/$slug'
      path: '/grocery-list/$slug'
      fullPath: '/grocery-list/$slug'
      preLoaderRoute: typeof GroceryListSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/$productId': {
      id: '/guide/$productId'
      path: '/guide/$productId'
      fullPath: '/guide/$productId'
      preLoaderRoute: typeof GuideProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$slug': {
      id: '/learn/$slug'
      path: '/learn/$slug'
      fullPath: '/learn/$slug'
      preLoaderRoute: typeof LearnSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/hub': {
      id: '/learn/hub'
      path: '/learn/hub'
      fullPath: '/learn/hub'
      preLoaderRoute: typeof LearnHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$slug': {
      id: '/product/$slug'
      path: '/product/$slug'
      fullPath: '/product/$slug'
      preLoaderRoute: typeof ProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/': {
      id: '/routines/'
      path: '/routines'
      fullPath: '/routines/'
      preLoaderRoute: typeof RoutinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/$bundleId': {
      id: '/routines/$bundleId'
      path: '/routines/$bundleId'
      fullPath: '/routines/$bundleId'
      preLoaderRoute: typeof RoutinesBundleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/issues/$id': {
      id: '/admin/issues/$id'
      path: '/admin/issues/$id'
      fullPath: '/admin/issues/$id'
      preLoaderRoute: typeof AdminIssuesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/article/$slug': {
      id: '/learn/article/$slug'
      path: '/learn/article/$slug'
      fullPath: '/learn/article/$slug'
      preLoaderRoute: typeof LearnArticleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/issue-cover/$id': {
      id: '/api/public/issue-cover/$id'
      path: '/api/public/issue-cover/$id'
      fullPath: '/api/public/issue-cover/$id'
      preLoaderRoute: typeof ApiPublicIssueCoverIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/signals/harvest': {
      id: '/api/public/signals/harvest'
      path: '/api/public/signals/harvest'
      fullPath: '/api/public/signals/harvest'
      preLoaderRoute: typeof ApiPublicSignalsHarvestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckoutRouteChildren {
  CheckoutReturnRoute: typeof CheckoutReturnRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutReturnRoute: CheckoutReturnRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  BrandsRoute: BrandsRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  ClubRoute: ClubRoute,
  ConsultationRoute: ConsultationRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  JourneyRoute: JourneyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RestockRoute: RestockRoute,
  ReturnsPolicyRoute: ReturnsPolicyRoute,
  ReviewsRoute: ReviewsRoute,
  SearchRoute: SearchRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SkinConcernsRoute: SkinConcernsRoute,
  TrackRoute: TrackRoute,
  WishlistRoute: WishlistRoute,
  AdminGuideLinksRoute: AdminGuideLinksRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSignalsRoute: AdminSignalsRoute,
  BlogSlugRoute: BlogSlugRoute,
  GroceryListSlugRoute: GroceryListSlugRoute,
  GuideProductIdRoute: GuideProductIdRoute,
  LearnSlugRoute: LearnSlugRoute,
  LearnHubRoute: LearnHubRoute,
  ProductSlugRoute: ProductSlugRoute,
  RoutinesBundleIdRoute: RoutinesBundleIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  GroceryListIndexRoute: GroceryListIndexRoute,
  LearnIndexRoute: LearnIndexRoute,
  RoutinesIndexRoute: RoutinesIndexRoute,
  AdminIssuesIdRoute: AdminIssuesIdRoute,
  LearnArticleSlugRoute: LearnArticleSlugRoute,
  ApiPublicIssueCoverIdRoute: ApiPublicIssueCoverIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicSignalsHarvestRoute: ApiPublicSignalsHarvestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
